version: '3.4'

services:
  ai-kakeibo-backend:
    container_name: ai-kakeibo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=db;Database=AiKakeiboDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "5000:8080"
      - "5001:8081"
